[package]
name = "wgpu-samples"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.13.1"
bytemuck_derive = "1.4.1"
futures = "0.3.28"
wgpu = { version = "0.16.0", features = [ "spirv" ] }
winit = "0.28.6"

[[bin]]
name = "hello-triangle"
path = "main.rs"
